@baseUrl = https://8080-dennisfaria-aulaarquite-39sl050p7jw.ws-us115.gitpod.io/

###
GET {{baseUrl}}/alunos

###
POST {{baseUrl}}/alunos
Content-Type: application/json

{
    "nome": "Dennis Farias"
}

###
GET {{baseUrl}}/alunos/2

###
PUT {{baseUrl}}/alunos/2
Content-Type: application/json

{
    "nome": ""
}

###
DELETE {{baseUrl}}/alunos/2
